import type { Stage } from "@/course/course.schema";

export const stage19 = {
  id: "stage-19",
  number: 19,
  title: "Object-Oriented Programming",
  summary:
    "Master Python classes, inheritance, encapsulation, and composition through worked examples and projects.",
  level: "intermediate",
  masteryGateConceptIds: [
    "class-definition",
    "inheritance",
    "encapsulation",
    "method-resolution-order",
  ],
  lessons: [
    {
      id: "s19-objects-and-identity",
      stageId: "stage-19",
      title: "Objects and Identity",
      kind: "concept",
      difficulty: "intermediate",
      objectives: [
        "Explain what an object is in Python",
        "Use id() and type() to inspect objects",
        "Distinguish identity from equality",
      ],
      prerequisites: [],
      concepts: ["class-definition"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Objects and Identity\n\nIn Python, **everything is an object** — integers, strings, functions, and class instances. Every object has:\n\n- **Identity** — unique integer from `id(obj)`, guaranteed unique for the object's lifetime\n- **Type** — the class it belongs to, from `type(obj)`\n- **Value** — the data it holds\n\n```python\nx = 42\nprint(id(x))    # e.g. 140234567890\nprint(type(x))  # <class 'int'>\n```",
        },
        {
          kind: "callout",
          variant: "info",
          title: "Identity vs equality",
          body: "`is` checks identity (same object in memory). `==` checks equality (same value). Two equal objects may not be identical.",
        },
        {
          kind: "code",
          language: "python",
          code: "a = [1, 2, 3]\nb = [1, 2, 3]\nc = a\nprint(a == b)  # True  -- same value\nprint(a is b)  # False -- different objects\nprint(a is c)  # True  -- same object",
          caption: "Identity vs equality in action",
        },
        {
          kind: "why-matters",
          body: "Understanding identity prevents aliasing bugs where two names point to the same mutable object and a change through one unexpectedly affects the other.",
        },
      ],
      interactions: [
        {
          id: "s19-identity-mc",
          kind: "multiple-choice",
          prompt: "After `x = [1, 2]; y = x`, what does `x is y` return?",
          beginnerPurpose: "Distinguish aliasing from copying",
          expectedConceptIds: ["class-definition"],
          options: [
            { id: "a", text: "True", isCorrect: true, explanation: "y = x makes y an alias — both names point to the same list object." },
            { id: "b", text: "False", isCorrect: false, explanation: "y = x[:] would create a copy. Plain assignment creates an alias." },
            { id: "c", text: "None", isCorrect: false, explanation: "'is' always returns a bool, never None." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "y = x copies the reference, not the list." }],
          feedback: { correct: "Correct! y is an alias for x.", incorrect: "y = x creates an alias — both point to the same object." },
        },
        {
          id: "s19-identity-predict",
          kind: "predict-output",
          prompt: "What does this print?",
          beginnerPurpose: "Trace identity and type inspection",
          expectedConceptIds: ["class-definition"],
          code: "a = \"hello\"\nb = \"hello\"\nprint(a == b)\nprint(type(a).__name__)",
          expectedOutput: "True\nstr",
          allowedAttempts: 3,
          hints: [{ level: "syntax", text: "__name__ returns the class name as a string." }],
          feedback: { correct: "Correct!", incorrect: "== compares values; type().__name__ gives the class name string." },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s19-identity-mc", "s19-identity-predict"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s19-class-definition",
      stageId: "stage-19",
      title: "Class Definition and Instance Creation",
      kind: "concept",
      difficulty: "intermediate",
      objectives: [
        "Define a class with the class keyword",
        "Implement __init__ to initialize instance state",
        "Create instances and call methods",
      ],
      prerequisites: ["s19-objects-and-identity"],
      concepts: ["class-definition"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Defining a Class\n\n```python\nclass Dog:\n    def __init__(self, name: str, breed: str) -> None:\n        self.name = name\n        self.breed = breed\n\n    def bark(self) -> str:\n        return f\"{self.name} says: Woof!\"\n\nfido = Dog(\"Fido\", \"Labrador\")\nprint(fido.bark())  # Fido says: Woof!\n```\n\n- `__init__` is called automatically when you create an instance\n- `self` refers to the specific instance being operated on\n- `self.name` stores data on the instance (instance variable)",
        },
        {
          kind: "mental-model",
          title: "Class as cookie cutter",
          analogy: "A class is a cookie cutter; instances are the cookies. The cutter defines shape; each cookie is separate.",
          explanation: "You can create as many instances as needed from one class, each with different attribute values.",
        },
        {
          kind: "callout",
          variant: "tip",
          title: "self is just a convention",
          body: "Python requires the first parameter of instance methods to receive the instance, but 'self' is a naming convention. Always use self — deviating confuses every reader.",
        },
      ],
      interactions: [
        {
          id: "s19-class-fill",
          kind: "fill-code",
          prompt: "Complete the class so it stores a radius and computes area.",
          beginnerPurpose: "Write a class from scratch",
          expectedConceptIds: ["class-definition"],
          codeTemplate: "import math\n\nclass Circle:\n    def __init__(self, radius: float) -> None:\n        self._____ = radius\n\n    def area(self) -> float:\n        return math.pi * self.radius ** 2",
          blanks: [{ placeholder: "_____", answer: "radius", caseSensitive: true }],
          allowedAttempts: 3,
          hints: [{ level: "syntax", text: "The attribute name should match what area() uses: self.radius." }],
          feedback: { correct: "Correct! self.radius stores the value on the instance.", incorrect: "Use self.radius to match what area() references." },
        },
        {
          id: "s19-class-run",
          kind: "run-code",
          prompt: "Define a class Point with x and y attributes and a distance_to_origin method returning sqrt(x**2 + y**2). Print the distance for Point(3, 4).",
          beginnerPurpose: "Build a class with a computed method",
          expectedConceptIds: ["class-definition"],
          starterCode: "import math\n\n# Define Point here\n",
          task: "Print 5.0",
          expectedOutputContains: ["5.0"],
          pyodideCompatible: true,
          allowedAttempts: 10,
          hints: [{ level: "concept", text: "Use self.x and self.y in the method body." }],
          feedback: { correct: "Correct!", incorrect: "Check that distance_to_origin uses math.sqrt(self.x**2 + self.y**2)." },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s19-class-fill", "s19-class-run"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s19-instance-vs-class-vars",
      stageId: "stage-19",
      title: "Instance Variables and Class Variables",
      kind: "concept",
      difficulty: "intermediate",
      objectives: [
        "Distinguish instance variables from class variables",
        "Explain when class variables are shared vs shadowed",
        "Avoid the mutable class variable pitfall",
      ],
      prerequisites: ["s19-class-definition"],
      concepts: ["class-definition"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Instance vs Class Variables\n\n**Instance variables** are defined in `__init__` via `self.name = ...`. Each instance has its own copy.\n\n**Class variables** are defined at class level. All instances share them.\n\n```python\nclass Dog:\n    species = \"Canis familiaris\"  # class variable\n\n    def __init__(self, name: str) -> None:\n        self.name = name  # instance variable\n\nprint(Dog.species)         # Canis familiaris\nprint(Dog(\"Rex\").species)  # Canis familiaris (inherited)\n```",
        },
        {
          kind: "callout",
          variant: "danger",
          title: "Mutable class variable pitfall",
          body: "Never use a mutable value (list, dict) as a class variable unless intentional. `items = []` at class level is shared across all instances. Use `self.items = []` in __init__.",
        },
        {
          kind: "comparison",
          leftLabel: "Mutable class variable — BUG",
          rightLabel: "Instance variable — CORRECT",
          leftCode: "class Cart:\n    items = []  # shared!\n\na, b = Cart(), Cart()\na.items.append('x')\nprint(b.items)  # ['x'] — oops!",
          rightCode: "class Cart:\n    def __init__(self):\n        self.items = []  # per-instance\n\na, b = Cart(), Cart()\na.items.append('x')\nprint(b.items)  # [] — correct",
        },
      ],
      interactions: [
        {
          id: "s19-vars-mc",
          kind: "multiple-choice",
          prompt: "You want every BankAccount to start with balance=0, unique per instance. Where do you define it?",
          beginnerPurpose: "Choose between instance and class variable",
          expectedConceptIds: ["class-definition"],
          options: [
            { id: "a", text: "At class level: `balance = 0`", isCorrect: false, explanation: "For integers this accidentally works due to int immutability, but the correct intent is __init__." },
            { id: "b", text: "In __init__: `self.balance = 0`", isCorrect: true, explanation: "Correct! self.balance = 0 in __init__ gives each instance its own balance." },
            { id: "c", text: "As a module-level variable", isCorrect: false, explanation: "Module-level variables are shared across all instances and break encapsulation." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Per-instance state belongs in __init__." }],
          feedback: { correct: "Correct! __init__ with self.balance = 0 gives each instance its own balance.", incorrect: "Use self.balance = 0 in __init__ for per-instance state." },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s19-vars-mc"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s19-encapsulation",
      stageId: "stage-19",
      title: "Encapsulation and Privacy Conventions",
      kind: "concept",
      difficulty: "intermediate",
      objectives: [
        "Apply the single-underscore convention for internal attributes",
        "Explain double-underscore name mangling",
        "Design a class with a clear public interface",
      ],
      prerequisites: ["s19-instance-vs-class-vars"],
      concepts: ["encapsulation"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Encapsulation Conventions\n\nPython uses naming conventions rather than access modifiers:\n\n- `name` — public: intended for external use\n- `_name` — internal: prefer using the provided methods\n- `__name` — name-mangled: renamed to `_ClassName__name`\n\n```python\nclass Account:\n    def __init__(self, balance: float) -> None:\n        self._balance = balance  # internal\n\n    def deposit(self, amount: float) -> None:\n        if amount > 0:\n            self._balance += amount\n\n    def get_balance(self) -> float:\n        return self._balance\n```",
        },
        {
          kind: "callout",
          variant: "info",
          title: "Conventions, not enforcement",
          body: "Single underscore is a social contract. Double underscore prevents accidental override in subclasses, not malicious access.",
        },
        {
          kind: "why-matters",
          body: "Encapsulation lets you change internal implementation without breaking callers. When users bypass _ prefixed attributes, they create hidden dependencies on internals.",
        },
      ],
      interactions: [
        {
          id: "s19-encap-mc",
          kind: "multiple-choice",
          prompt: "Attribute `__secret` in class `Vault` is accessed externally as what mangled name?",
          beginnerPurpose: "Understand name mangling",
          expectedConceptIds: ["encapsulation"],
          options: [
            { id: "a", text: "vault.__secret", isCorrect: false, explanation: "Double underscore triggers name mangling — the attribute is renamed." },
            { id: "b", text: "vault._Vault__secret", isCorrect: true, explanation: "Correct! Python mangles __secret to _Vault__secret." },
            { id: "c", text: "vault.secret", isCorrect: false, explanation: "Mangling transforms the name, it doesn't strip underscores." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "syntax", text: "Mangled name = _ClassName + double-underscore-attribute-name." }],
          feedback: { correct: "Correct! Name mangling prefixes with _ClassName.", incorrect: "Double underscore becomes _ClassName__name." },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s19-encap-mc"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s19-inheritance",
      stageId: "stage-19",
      title: "Inheritance and super()",
      kind: "concept",
      difficulty: "intermediate",
      objectives: [
        "Define a subclass that inherits from a base class",
        "Use super() to call parent methods",
        "Override methods to change behavior in subclasses",
      ],
      prerequisites: ["s19-encapsulation"],
      concepts: ["inheritance"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Inheritance\n\nA subclass inherits all methods and attributes and can override them:\n\n```python\nclass Animal:\n    def __init__(self, name: str) -> None:\n        self.name = name\n\n    def speak(self) -> str:\n        return f\"{self.name} makes a sound\"\n\nclass Dog(Animal):\n    def speak(self) -> str:\n        return f\"{self.name} says: Woof!\"\n\nfor animal in [Dog(\"Rex\"), Animal(\"Unknown\")]:\n    print(animal.speak())\n```",
        },
        {
          kind: "text",
          markdown:
            "## super()\n\n`super()` calls the parent implementation. Use it when extending rather than replacing:\n\n```python\nclass Employee(Person):\n    def __init__(self, name: str, dept: str) -> None:\n        super().__init__(name)  # initialize Person part\n        self.department = dept\n```",
        },
        {
          kind: "callout",
          variant: "tip",
          title: "Always call super().__init__",
          body: "When overriding __init__, call super().__init__() first. Skipping it leaves parent attributes uninitialized.",
        },
      ],
      interactions: [
        {
          id: "s19-inherit-fill",
          kind: "fill-code",
          prompt: "Complete the Employee subclass that adds a department attribute.",
          beginnerPurpose: "Use super() in __init__",
          expectedConceptIds: ["inheritance"],
          codeTemplate: "class Person:\n    def __init__(self, name: str) -> None:\n        self.name = name\n\nclass Employee(Person):\n    def __init__(self, name: str, dept: str) -> None:\n        _____().__init__(name)\n        self.department = dept",
          blanks: [{ placeholder: "_____", answer: "super", caseSensitive: true }],
          allowedAttempts: 3,
          hints: [{ level: "syntax", text: "The function that calls the parent is super()." }],
          feedback: { correct: "Correct! super().__init__(name) initializes the Person part.", incorrect: "Use super() to call the parent __init__." },
        },
        {
          id: "s19-inherit-predict",
          kind: "predict-output",
          prompt: "What does this print?",
          beginnerPurpose: "Trace method override",
          expectedConceptIds: ["inheritance"],
          code: "class Base:\n    def greet(self) -> str:\n        return \"Hello from Base\"\n\nclass Child(Base):\n    def greet(self) -> str:\n        return super().greet() + \" and Child\"\n\nprint(Child().greet())",
          expectedOutput: "Hello from Base and Child",
          allowedAttempts: 3,
          hints: [{ level: "concept", text: "super().greet() returns the Base version, then ' and Child' is appended." }],
          feedback: { correct: "Correct!", incorrect: "super().greet() returns 'Hello from Base', then + ' and Child'." },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s19-inherit-fill", "s19-inherit-predict"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s19-mro",
      stageId: "stage-19",
      title: "Method Resolution Order",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Explain how Python resolves method calls in a class hierarchy",
        "Use __mro__ to inspect resolution order",
        "Understand C3 linearization for multiple inheritance",
      ],
      prerequisites: ["s19-inheritance"],
      concepts: ["method-resolution-order"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Method Resolution Order (MRO)\n\nPython uses the C3 linearization algorithm to determine which class's method is called. Inspect it with `ClassName.__mro__`:\n\n```python\nclass A:\n    def hello(self): return \"A\"\n\nclass B(A):\n    def hello(self): return \"B\"\n\nclass C(A):\n    pass\n\nclass D(B, C):\n    pass\n\nprint(D.__mro__)\n# D -> B -> C -> A -> object\nprint(D().hello())  # \"B\"\n```",
        },
        {
          kind: "callout",
          variant: "info",
          title: "Left-to-right, depth-first, no repeats",
          body: "C3 MRO searches left-to-right, ensures each class appears once, and guarantees parents appear after their children. This prevents inconsistencies in diamond inheritance.",
        },
        {
          kind: "why-matters",
          body: "MRO determines which method wins in multiple inheritance. Understanding it prevents surprising super() call chains in mixin-based designs.",
        },
      ],
      interactions: [
        {
          id: "s19-mro-mc",
          kind: "multiple-choice",
          prompt: "For `class D(B, C)` where both B and C define `foo()`, which `foo()` does `D().foo()` call?",
          beginnerPurpose: "Predict MRO-based dispatch",
          expectedConceptIds: ["method-resolution-order"],
          options: [
            { id: "a", text: "B.foo()", isCorrect: true, explanation: "B appears before C in D's MRO (D → B → C → ...), so B.foo() is found first." },
            { id: "b", text: "C.foo()", isCorrect: false, explanation: "C is after B in the MRO for D(B, C)." },
            { id: "c", text: "Both are called", isCorrect: false, explanation: "Python stops at the first MRO match. Only B.foo() is called." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "MRO for D(B, C): D first, then B (left parent), then C." }],
          feedback: { correct: "Correct! MRO searches left to right.", incorrect: "MRO for D(B, C) checks B before C." },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s19-mro-mc"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s19-composition",
      stageId: "stage-19",
      title: "Composition over Inheritance",
      kind: "concept",
      difficulty: "intermediate",
      objectives: [
        "Apply composition to combine behaviors without inheritance",
        "Decide when to use inheritance vs composition",
        "Design flexible classes using has-a relationships",
      ],
      prerequisites: ["s19-mro"],
      concepts: ["inheritance"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Composition\n\nComposition means a class **contains** objects rather than **inheriting** from them. Use composition for \"has-a\" relationships:\n\n```python\nclass Engine:\n    def start(self) -> str:\n        return \"Vroom!\"\n\nclass Car:\n    def __init__(self) -> None:\n        self.engine = Engine()  # HAS-A Engine\n\n    def drive(self) -> str:\n        return self.engine.start()\n```\n\nA Car is not an Engine — it has one. Using inheritance here would be wrong.",
        },
        {
          kind: "comparison",
          leftLabel: "Wrong: inheritance for has-a",
          rightLabel: "Right: composition",
          leftCode: "class Logger(File):  # Logger IS a File? No!\n    def log(self, msg: str) -> None:\n        self.write(msg + '\\n')",
          rightCode: "class Logger:\n    def __init__(self, file) -> None:\n        self._file = file  # HAS a file\n    def log(self, msg: str) -> None:\n        self._file.write(msg + '\\n')",
        },
        {
          kind: "callout",
          variant: "tip",
          title: "Favor composition over inheritance",
          body: "Inheritance creates tight coupling and can't be changed at runtime. Composition lets you swap implementations (inject a mock for testing) and avoids MRO complexity.",
        },
      ],
      interactions: [
        {
          id: "s19-comp-mc",
          kind: "multiple-choice",
          prompt: "A Notifier sends emails using an EmailClient. Which design is correct?",
          beginnerPurpose: "Apply is-a vs has-a rule",
          expectedConceptIds: ["inheritance"],
          options: [
            { id: "a", text: "class Notifier(EmailClient) — inheritance", isCorrect: false, explanation: "A Notifier is not an EmailClient — it uses one." },
            { id: "b", text: "class Notifier with self.client = EmailClient() — composition", isCorrect: true, explanation: "Correct! Notifier HAS an email client. Composition enables swapping to SMS later." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Is a Notifier a type of EmailClient? No — it uses one." }],
          feedback: { correct: "Correct! Composition models has-a.", incorrect: "A Notifier uses an EmailClient but isn't one — use composition." },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s19-comp-mc"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
  ],
  project: {
    id: "s19-project",
    stageId: "stage-19",
    title: "OOP Design Project: Library Catalog",
    brief:
      "Design and implement a class hierarchy for a library catalog. Use inheritance for item types (Book, DVD, Magazine), encapsulation for internal state, and composition for the Catalog.",
    requirements: [
      "Base class LibraryItem with title, id, is_checked_out",
      "Subclasses Book (+ author), DVD (+ runtime_minutes), Magazine (+ issue_number)",
      "Catalog class composing a list of LibraryItems",
      "Methods: checkout(), return_item(), search_by_title()",
      "Type annotations on all public methods",
    ],
    acceptanceCriteria: [
      "All item types work with the catalog via the base class interface",
      "Checkout and return update state correctly",
      "Search works across all item types",
    ],
    conceptIds: ["class-definition", "inheritance", "encapsulation"],
    difficulty: "intermediate",
  },
} satisfies Stage;
