import type { Stage } from "@/course/course.schema";

export const stage16 = {
  id: "stage-16",
  number: 16,
  title: "Architecture and Capstone",
  summary:
    "Design, implement, test, document, and explain a complete Python project using everything learned.",
  level: "advanced",
  masteryGateConceptIds: [
    "system-design",
    "separation-of-concerns",
    "interface-design",
    "error-resilience",
    "documentation",
    "runbook",
  ],
  lessons: [
    {
      id: "s16-system-design-principles",
      stageId: "stage-16",
      title: "System Design Principles",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Apply separation of concerns to split code into focused modules",
        "Identify boundaries between I/O, business logic, and presentation",
        "Design a module structure before writing code",
      ],
      prerequisites: ["s15-security-review"],
      concepts: ["system-design", "separation-of-concerns"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Separation of Concerns\n\nGood code is divided into layers with clear responsibilities:\n\n- **I/O layer** — reading files, calling APIs, receiving user input\n- **Domain/logic layer** — business rules, data processing, validation\n- **Presentation layer** — formatting output, rendering UI\n\nEach layer should be testable in isolation. The domain layer should have no I/O — pass data in, get data out.",
        },
        {
          kind: "comparison",
          leftLabel: "Mixed concerns — hard to test",
          rightLabel: "Separated concerns — easy to test",
          leftCode: 'def process_file(path: str) -> None:\n    # Reads, processes, AND prints — all in one\n    with open(path) as f:\n        data = f.read()\n    result = data.upper()\n    print(result)',
          rightCode: 'def read_file(path: str) -> str:    # I/O\n    with open(path) as f:\n        return f.read()\n\ndef transform(data: str) -> str:    # Logic\n    return data.upper()\n\ndef display(result: str) -> None:   # Presentation\n    print(result)',
        },
        {
          kind: "callout",
          variant: "tip",
          title: "Test the domain layer without I/O",
          body: "When your business logic has no I/O dependencies, you can test it with plain function calls — no mocking needed. This makes tests fast, deterministic, and easy to write.",
        },
        {
          kind: "why-matters",
          body: "Separating concerns means your code can grow without becoming a tangled mess. Changes to I/O format don't affect business logic. New output formats don't require rewriting validation.",
        },
      ],
      interactions: [
        {
          id: "s16-design-i1",
          kind: "multiple-choice",
          prompt: "Which layer should handle reading a CSV file?",
          beginnerPurpose: "Place I/O in the correct layer",
          expectedConceptIds: ["separation-of-concerns"],
          options: [
            { id: "a", text: "Domain/logic layer", isCorrect: false, explanation: "Domain layer should be I/O free." },
            { id: "b", text: "I/O layer", isCorrect: true, explanation: "Correct! File reading is I/O and belongs in the I/O layer." },
            { id: "c", text: "Presentation layer", isCorrect: false, explanation: "Presentation layer formats output, not input." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "I/O = anything touching the filesystem, network, or console" }],
          feedback: {
            correct: "Correct! File reading is I/O and belongs in the I/O layer.",
            incorrect: "Anything touching files, network, or console is I/O.",
          },
        },
        {
          id: "s16-design-i2",
          kind: "plain-language-explain",
          prompt: "Explain separation of concerns in your own words with a real-world analogy",
          beginnerPurpose: "Articulate a core design principle",
          expectedConceptIds: ["system-design", "separation-of-concerns"],
          code: "# I/O: read_file(), call_api(), get_user_input()\n# Logic: validate(), transform(), calculate()\n# Output: format_report(), print_table()",
          keyPointsToHit: [
            "Each part of the code has one clear responsibility",
            "Changing one part doesn't break others",
            "Each layer is independently testable",
          ],
          sampleAnswer:
            "Separation of concerns means each part of your code does one thing only. Like a restaurant: the kitchen cooks (logic), the waiter takes orders and delivers food (I/O), and the menu describes what's available (presentation). If you change the menu, you don't rewrite the kitchen. Each part is independent and can be changed without breaking the others.",
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think of a real system with distinct roles, like a restaurant or assembly line" }],
          feedback: {
            correct: "Well explained with a clear analogy!",
            incorrect: "Use an analogy where different roles are clearly separated and independent.",
          },
        },
        {
          id: "s16-design-i3",
          kind: "reorder-code",
          prompt: "Arrange these to create a properly separated 3-layer structure",
          beginnerPurpose: "Practice separation of concerns in code organisation",
          expectedConceptIds: ["system-design"],
          lines: [
            "result = process(raw_data)  # domain",
            "raw_data = read_csv(path)    # I/O",
            "print_report(result)         # presentation",
            "def main():",
          ],
          correctOrder: [3, 1, 0, 2],
          allowedAttempts: 3,
          hints: [{ level: "structural", text: "def main() first, then I/O, then logic, then presentation" }],
          feedback: {
            correct: "Correct! main() → read (I/O) → process (logic) → print (presentation).",
            incorrect: "Structure: define main, read data, process data, display results.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s16-design-i1", "s16-design-i2", "s16-design-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s16-designing-interfaces",
      stageId: "stage-16",
      title: "Designing Clean Interfaces",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Apply the principle that functions should have one clear input and output",
        "Prefer explicit return values over modifying mutable arguments",
        "Use type hints as interface documentation",
      ],
      prerequisites: ["s16-system-design-principles"],
      concepts: ["interface-design"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## What Makes a Good Interface?\n\nA function's interface is its public contract: the types and meanings of its inputs and outputs.\n\nGood interface principles:\n- **Clear name** — says what it does, not how\n- **Pure when possible** — same input always gives same output\n- **Explicit returns** — returns data, doesn't modify shared state\n- **Type hints** — document the contract\n- **Single responsibility** — does one thing",
        },
        {
          kind: "comparison",
          leftLabel: "Unclear interface",
          rightLabel: "Clear interface",
          leftCode: "def process(x, data, flag=False):\n    # What is x? What does flag do?\n    # Returns what? Modifies data?\n    if flag:\n        data.append(x * 2)\n    return x",
          rightCode: "def double_and_append(\n    value: int,\n    collection: list[int],\n) -> list[int]:\n    \"\"\"Return a new list with value*2 appended.\"\"\"\n    return [*collection, value * 2]",
        },
        {
          kind: "code",
          language: "python",
          code: "from typing import Protocol\n\n# Protocol defines a structural interface\nclass DataStore(Protocol):\n    def save(self, key: str, value: bytes) -> None: ...\n    def load(self, key: str) -> bytes | None: ...\n\n# Any class that implements save() and load() satisfies this\nclass FileStore:\n    def save(self, key: str, value: bytes) -> None:\n        with open(key, 'wb') as f:\n            f.write(value)\n\n    def load(self, key: str) -> bytes | None:\n        try:\n            with open(key, 'rb') as f:\n                return f.read()\n        except FileNotFoundError:\n            return None",
          caption: "Protocol for structural typing",
        },
      ],
      interactions: [
        {
          id: "s16-interface-i1",
          kind: "multiple-choice",
          prompt: "A function receives a list and appends to it as a side effect without returning anything. What is wrong with this interface?",
          beginnerPurpose: "Recognise problematic mutable side effects",
          expectedConceptIds: ["interface-design"],
          options: [
            { id: "a", text: "Nothing — this is a common pattern", isCorrect: false, explanation: "Mutating arguments silently creates hidden coupling." },
            { id: "b", text: "It mutates the caller's data silently, creating hidden coupling", isCorrect: true, explanation: "Correct! Prefer returning a new list over mutating the input." },
            { id: "c", text: "Functions can't receive lists", isCorrect: false, explanation: "Functions can receive any type." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "The caller doesn't know their list was modified unless they read the implementation" }],
          feedback: {
            correct: "Correct! Silent mutation creates surprising coupling between caller and function.",
            incorrect: "Mutating the caller's data without returning makes the function unpredictable from the outside.",
          },
        },
        {
          id: "s16-interface-i2",
          kind: "fill-code",
          prompt: "Complete the type hints to document this function's interface",
          beginnerPurpose: "Practice type hints as interface documentation",
          expectedConceptIds: ["interface-design"],
          codeTemplate:
            "def find_by_id(\n    records: list[___BLANK_1___],\n    target_id: ___BLANK_2___,\n) -> dict | ___BLANK_3___:\n    for r in records:\n        if r.get('id') == target_id:\n            return r\n    return None",
          blanks: [
            { placeholder: "___BLANK_1___", answer: "dict", caseSensitive: true },
            { placeholder: "___BLANK_2___", answer: "int", caseSensitive: true },
            { placeholder: "___BLANK_3___", answer: "None", caseSensitive: true },
          ],
          allowedAttempts: 3,
          hints: [{ level: "syntax", text: "list[dict], int, and None | dict for optional return" }],
          feedback: {
            correct: "Correct! Type hints document the contract clearly.",
            incorrect: "Use dict for records items, int for id, None for the no-match case.",
          },
        },
        {
          id: "s16-interface-i3",
          kind: "predict-output",
          prompt: "What does this pure function return?",
          beginnerPurpose: "Verify understanding of pure functions",
          expectedConceptIds: ["interface-design"],
          code: "def add_item(items: list[str], new_item: str) -> list[str]:\n    return [*items, new_item]\n\noriginal = ['a', 'b']\nresult = add_item(original, 'c')\nprint(original)\nprint(result)",
          expectedOutput: "['a', 'b']\n['a', 'b', 'c']",
          allowedAttempts: 3,
          hints: [{ level: "concept", text: "The function returns a NEW list, it does not modify 'original'" }],
          feedback: {
            correct: "Correct! The function creates a new list, leaving original unchanged.",
            incorrect: "[*items, new_item] creates a new list — original is untouched.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s16-interface-i1", "s16-interface-i2", "s16-interface-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s16-error-resilience-patterns",
      stageId: "stage-16",
      title: "Error Resilience Patterns",
      kind: "practice",
      difficulty: "advanced",
      objectives: [
        "Apply the Result type pattern instead of raising exceptions for expected failures",
        "Design systems that degrade gracefully",
        "Write recovery paths for all failure modes",
      ],
      prerequisites: ["s16-designing-interfaces"],
      concepts: ["error-resilience"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Expected vs Unexpected Failures\n\n**Unexpected** (bugs): raise exceptions — you want to know immediately.\n**Expected** (normal operation failures): use Result types or explicit error returns.\n\nThe Result pattern (from functional programming) makes failure an explicit part of the type signature:\n```python\ntype Result[T] = T | Error\n```",
        },
        {
          kind: "code",
          language: "python",
          code: "from dataclasses import dataclass\nfrom typing import TypeVar, Generic\n\nT = TypeVar('T')\n\n@dataclass(frozen=True)\nclass Ok(Generic[T]):\n    value: T\n    ok: bool = True\n\n@dataclass(frozen=True)\nclass Err:\n    message: str\n    ok: bool = False\n\ntype Result = Ok | Err\n\ndef parse_age(text: str) -> Result:\n    try:\n        age = int(text)\n    except ValueError:\n        return Err(f\"'{text}' is not a valid age\")\n    if age < 0 or age > 150:\n        return Err(f\"Age {age} is out of valid range\")\n    return Ok(age)\n\n# Usage\nfor raw in ['25', '-5', 'abc', '30']:\n    result = parse_age(raw)\n    if result.ok:\n        print(f\"Valid age: {result.value}\")\n    else:\n        print(f\"Error: {result.message}\")",
          caption: "Result type pattern for expected failures",
        },
      ],
      interactions: [
        {
          id: "s16-resilience-i1",
          kind: "multiple-choice",
          prompt: "When is the Result type pattern more appropriate than raising an exception?",
          beginnerPurpose: "Know when to use Result vs exceptions",
          expectedConceptIds: ["error-resilience"],
          options: [
            { id: "a", text: "For programming bugs like AttributeError", isCorrect: false, explanation: "Bugs should raise exceptions — you want to crash immediately." },
            { id: "b", text: "For expected failures like invalid user input or missing files", isCorrect: true, explanation: "Correct! Expected failures are part of normal operation and should be explicit in the return type." },
            { id: "c", text: "For all errors — never use exceptions", isCorrect: false, explanation: "Unexpected errors (bugs) should still raise exceptions." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Ask: is this failure expected in normal use, or is it a programming bug?" }],
          feedback: {
            correct: "Correct! Expected failures belong in the return type; unexpected ones raise exceptions.",
            incorrect: "Use Result for expected failures (invalid input, missing resource). Raise exceptions for bugs.",
          },
        },
        {
          id: "s16-resilience-i2",
          kind: "predict-output",
          prompt: "What does this Result-based code print?",
          beginnerPurpose: "Trace Result pattern usage",
          expectedConceptIds: ["error-resilience"],
          code: "from dataclasses import dataclass\n\n@dataclass\nclass Ok:\n    value: object\n    ok: bool = True\n\n@dataclass\nclass Err:\n    message: str\n    ok: bool = False\n\ndef divide(a: int, b: int):\n    if b == 0:\n        return Err('Division by zero')\n    return Ok(a // b)\n\nr = divide(10, 0)\nprint(r.ok)\nprint(r.message)",
          expectedOutput: "False\nDivision by zero",
          allowedAttempts: 3,
          hints: [{ level: "concept", text: "divide(10, 0) hits the b==0 branch and returns Err" }],
          feedback: {
            correct: "Correct! Err has ok=False and a message.",
            incorrect: "b==0 returns Err with ok=False and message='Division by zero'.",
          },
        },
        {
          id: "s16-resilience-i3",
          kind: "plain-language-explain",
          prompt: "Explain the concept of graceful degradation and give a concrete example",
          beginnerPurpose: "Articulate resilience thinking",
          expectedConceptIds: ["error-resilience"],
          code: "# If the cache fails, fall back to the database\n# If the database is slow, return a default\n# If the default fails, show a maintenance message",
          keyPointsToHit: [
            "The system continues to work when parts fail",
            "It provides reduced functionality rather than complete failure",
            "A concrete fallback chain is described",
          ],
          sampleAnswer:
            "Graceful degradation means the system keeps working at reduced capacity when parts fail, rather than crashing completely. For example: a search feature first tries a fast cache; if the cache fails, it falls back to the database; if the database is slow, it returns partial results with a warning; only if everything fails does it show an error. Users get some value even when the system has problems.",
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think: what is the fallback when the primary approach fails?" }],
          feedback: {
            correct: "Well explained! You described a concrete fallback chain.",
            incorrect: "Describe a scenario where a system provides reduced function instead of failing completely.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s16-resilience-i1", "s16-resilience-i2", "s16-resilience-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s16-documentation-practices",
      stageId: "stage-16",
      title: "Documentation Practices",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Write useful docstrings for modules, classes, and functions",
        "Create a minimal README with setup and usage",
        "Write a runbook for operational concerns",
      ],
      prerequisites: ["s16-error-resilience-patterns"],
      concepts: ["documentation", "runbook"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## What Good Documentation Covers\n\n**Docstrings** (in code):\n- What the function does, not how\n- Parameters and return type (if not obvious from hints)\n- Exceptions raised\n- One short example if helpful\n\n**README** (for humans):\n- What the project does\n- How to install and run\n- How to run tests\n- Configuration (env vars)\n\n**Runbook** (for operations):\n- Common failure modes and how to recover\n- How to deploy\n- How to roll back",
        },
        {
          kind: "code",
          language: "python",
          code: '"""Task manager CLI — manage personal tasks stored in a JSON file."""\n\nfrom pathlib import Path\n\n\ndef load_tasks(path: Path) -> list[dict]:\n    """Load tasks from a JSON file.\n\n    Args:\n        path: Path to the JSON tasks file.\n\n    Returns:\n        List of task dicts, each with \'id\', \'title\', and \'done\'.\n\n    Raises:\n        FileNotFoundError: If the tasks file does not exist.\n        ValueError: If the file contains invalid JSON.\n    """\n    import json\n    try:\n        with open(path, encoding="utf-8") as f:\n            return json.load(f)\n    except json.JSONDecodeError as e:\n        raise ValueError(f"Invalid JSON in {path}: {e}") from e',
          caption: "Well-documented function with docstring",
        },
        {
          kind: "callout",
          variant: "tip",
          title: "Document the 'why', not the 'what'",
          body: "Type hints already document types. Docstrings should explain purpose, constraints, and non-obvious behaviour. 'Loads tasks from JSON' is obvious. 'Returns empty list if file is missing (not an error)' is valuable.",
        },
      ],
      interactions: [
        {
          id: "s16-docs-i1",
          kind: "multiple-choice",
          prompt: "What should a function's docstring primarily document?",
          beginnerPurpose: "Know what belongs in docstrings",
          expectedConceptIds: ["documentation"],
          options: [
            { id: "a", text: "A line-by-line explanation of the implementation", isCorrect: false, explanation: "That's comments in the code, not docstrings." },
            { id: "b", text: "The purpose, inputs, outputs, and important exceptions", isCorrect: true, explanation: "Correct! Docstrings document the contract, not the implementation." },
            { id: "c", text: "The author's name and date", isCorrect: false, explanation: "Authorship belongs in git blame, not docstrings." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Docstrings are for callers, not for people reading the implementation" }],
          feedback: {
            correct: "Correct! Docstrings document the contract: what it does, not how.",
            incorrect: "Docstrings document what a function does for its callers — purpose, inputs, outputs.",
          },
        },
        {
          id: "s16-docs-i2",
          kind: "fill-code",
          prompt: "Complete the docstring for this function",
          beginnerPurpose: "Practice writing informative docstrings",
          expectedConceptIds: ["documentation"],
          codeTemplate:
            'def clamp(value: float, minimum: float, maximum: float) -> float:\n    """___BLANK_1___.\n\n    Returns minimum if value < minimum,\n    maximum if value > maximum,\n    otherwise value unchanged.\n    """\n    return max(minimum, min(maximum, value))',
          blanks: [
            { placeholder: "___BLANK_1___", answer: "Clamp value to the range [minimum, maximum]", caseSensitive: false },
          ],
          allowedAttempts: 3,
          hints: [{ level: "concept", text: "The first line should be a concise summary of what the function does" }],
          feedback: {
            correct: "Good docstring! The first line summarises the purpose concisely.",
            incorrect: "The first line of a docstring should be a one-sentence summary of the function's purpose.",
          },
        },
        {
          id: "s16-docs-i3",
          kind: "plain-language-explain",
          prompt: "Explain the difference between a README and a runbook, and what each should contain",
          beginnerPurpose: "Know what documentation artefacts a production project needs",
          expectedConceptIds: ["documentation"],
          code: "# README.md — for developers\n# RUNBOOK.md — for operations",
          keyPointsToHit: [
            "README is for developers: setup, usage, testing",
            "Runbook is for operations: failures, deploy, rollback",
            "They serve different audiences",
          ],
          sampleAnswer:
            "A README is for developers who want to understand, set up, and contribute to the project. It covers: what the project does, how to install it, how to run it, and how to run tests. A runbook is for operations: it describes what to do when things go wrong — common failure modes, how to deploy, how to roll back a bad release. They serve different audiences at different times.",
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "README = how to build/run; Runbook = how to recover when it breaks" }],
          feedback: {
            correct: "Well explained! Two different audiences with different needs.",
            incorrect: "Distinguish: README for dev setup and usage, runbook for operational incidents.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s16-docs-i1", "s16-docs-i2", "s16-docs-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s16-capstone-review",
      stageId: "stage-16",
      title: "Capstone Review and Defence",
      kind: "assessment",
      difficulty: "advanced",
      objectives: [
        "Review your capstone project against all mastery criteria",
        "Articulate every design decision made",
        "Identify one thing you would change with hindsight",
      ],
      prerequisites: ["s16-documentation-practices"],
      concepts: ["system-design", "documentation"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Capstone Defence\n\nThis is the final lesson. You've built a complete Python project. Now defend it.\n\n**Review checklist:**\n- Does the code have separation of concerns?\n- Are all inputs validated?\n- Are secrets from environment variables?\n- Are there unit tests with good coverage?\n- Does the README explain setup and usage?\n- Does the runbook cover failure modes?\n- Is the API documented with type hints and docstrings?\n- Could another developer run this without your help?",
        },
        {
          kind: "callout",
          variant: "success",
          title: "You've reached master level",
          body: "You've covered all 16 stages: from your first print() to async patterns, from if statements to security reviews, from single scripts to properly packaged software. What matters now is applying it — build things, read other people's code, and keep learning.",
        },
        {
          kind: "why-matters",
          body: "Technical skill without reflection doesn't compound. By articulating your design decisions and identifying improvements, you're developing the meta-skill that distinguishes experienced developers: the ability to critique your own work and grow from it.",
        },
      ],
      interactions: [
        {
          id: "s16-capstone-i1",
          kind: "plain-language-explain",
          prompt: "Explain the most important thing you learned in this course and how you would use it",
          beginnerPurpose: "Reflect on the course and consolidate the most valuable insight",
          expectedConceptIds: ["system-design"],
          code: "# No code — this is reflection",
          keyPointsToHit: [
            "Identifies a specific concept or pattern",
            "Explains why it matters in practice",
            "Gives a concrete application or example",
          ],
          sampleAnswer:
            "The most important thing I learned is separation of concerns. Before, I would write everything in one function — reading files, processing data, and printing results all mixed together. Now I split code into I/O, logic, and presentation layers. This matters because the logic becomes testable without any file system, the I/O can change without touching the business rules, and the code is much easier to reason about and maintain.",
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think about a concept that changed how you think about writing code" }],
          feedback: {
            correct: "Well reflected. The ability to articulate what you learned and why it matters is itself a master-level skill.",
            incorrect: "Be specific — name a concept, explain why it matters, and give an example of where you'd apply it.",
          },
        },
        {
          id: "s16-capstone-i2",
          kind: "multiple-choice",
          prompt: "Which of these is the strongest sign that Python code is production-ready?",
          beginnerPurpose: "Recognise production-readiness criteria",
          expectedConceptIds: ["documentation", "error-resilience"],
          options: [
            { id: "a", text: "It uses the newest Python features", isCorrect: false, explanation: "Novelty isn't a quality metric." },
            { id: "b", text: "It has tests, type hints, handles errors gracefully, and is documented", isCorrect: true, explanation: "Correct! These are the signs of code that can be maintained and trusted." },
            { id: "c", text: "It has no comments", isCorrect: false, explanation: "Minimal comments can be fine, but alone this isn't a quality signal." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think about what makes code trustworthy and maintainable" }],
          feedback: {
            correct: "Correct! Tests, types, error handling, and documentation are the hallmarks of production quality.",
            incorrect: "Production code is tested, typed, error-resilient, and documented.",
          },
        },
        {
          id: "s16-capstone-i3",
          kind: "multiple-choice",
          prompt: "A junior developer on your team asks: 'When is code done?' What is the best answer?",
          beginnerPurpose: "Internalise a professional mindset about software quality",
          expectedConceptIds: ["system-design"],
          options: [
            { id: "a", text: "When all tests pass", isCorrect: false, explanation: "Tests passing is necessary but not sufficient." },
            { id: "b", text: "When it runs without errors", isCorrect: false, explanation: "Running without errors in the happy path doesn't mean edge cases are handled." },
            { id: "c", text: "When another developer can understand, run, test, and maintain it without asking you for help", isCorrect: true, explanation: "Correct! Code is done when it can live independently of its original author." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think about what it means for code to be self-sufficient" }],
          feedback: {
            correct: "Exactly right. Code is done when it's independently maintainable.",
            incorrect: "Code is done when another developer can understand, run, test, and maintain it without your help.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s16-capstone-i1", "s16-capstone-i2", "s16-capstone-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
  ],
  project: {
    id: "s16-project",
    stageId: "stage-16",
    title: "Final Capstone: Personal Task Manager CLI",
    brief:
      "Build a complete, production-quality personal task manager CLI with file persistence, type hints, tests, documentation, and a runbook. Apply every principle from the course.",
    requirements: [
      "CLI with subcommands: add, list, complete, delete",
      "Tasks stored in JSON file via pathlib.Path",
      "All config (file path) from environment variables",
      "Type hints on all public functions",
      "Docstrings on all public functions",
      "Unit tests covering happy path and error cases",
      "README.md with setup and usage",
      "Separation: I/O module, domain module, CLI module",
      "Graceful error handling — no raw tracebacks to users",
    ],
    acceptanceCriteria: [
      "All subcommands work correctly",
      "JSON persists between runs",
      "Unit tests pass",
      "Another developer can set it up from README alone",
    ],
    conceptIds: [
      "system-design",
      "separation-of-concerns",
      "interface-design",
      "error-resilience",
      "documentation",
      "file-io",
      "cli-argument",
      "type-hint",
      "unit-test",
      "secrets-management",
    ],
    difficulty: "advanced",
    starterCode:
      "# task_manager/\n#   __init__.py\n#   io.py        -- file operations\n#   domain.py    -- task logic (no I/O)\n#   cli.py       -- argparse entry point\n#\n# tests/\n#   test_domain.py\n#\n# pyproject.toml\n# README.md\n# RUNBOOK.md\n",
  },
} satisfies Stage;
