import type { Stage } from "@/course/course.schema";

export const stage15 = {
  id: "stage-15",
  number: 15,
  title: "Security, Packaging, and Distribution",
  summary:
    "Handle secrets safely, manage dependencies, structure packages for distribution, use semantic versioning, and understand supply-chain risk.",
  level: "advanced",
  masteryGateConceptIds: [
    "secrets-management",
    "env-variables",
    "dependency-pinning",
    "package-structure",
    "semantic-versioning",
    "pyproject-toml",
    "supply-chain-risk",
  ],
  lessons: [
    {
      id: "s15-secrets-env-variables",
      stageId: "stage-15",
      title: "Secrets and Environment Variables",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Never hardcode secrets in source code",
        "Load secrets from environment variables using os.environ",
        "Use python-dotenv for local development",
      ],
      prerequisites: ["s14-async-patterns"],
      concepts: ["secrets-management", "env-variables"],
      contentBlocks: [
        {
          kind: "callout",
          variant: "danger",
          title: "Never commit secrets to git",
          body: "Hardcoded passwords, API keys, and tokens in source files get committed to git history forever. Even if you delete them, they remain in old commits. Use environment variables instead.",
        },
        {
          kind: "text",
          markdown:
            "## The Environment Variable Pattern\n\nSecrets belong in the environment, not in code:\n\n1. Load from `os.environ` at startup\n2. Fail fast if a required secret is missing\n3. Use a `.env` file for local dev (never commit it — add to `.gitignore`)\n4. Use your platform's secrets manager in production (Koyeb env vars, etc.)",
        },
        {
          kind: "code",
          language: "python",
          code: 'import os\n\n# Load required secret — fail fast if missing\ndef require_env(key: str) -> str:\n    """Load an environment variable or raise if not set."""\n    value = os.environ.get(key)\n    if not value:\n        raise RuntimeError(\n            f"Required environment variable {key!r} is not set. "\n            "Set it in your environment or .env file."\n        )\n    return value\n\n# Usage — at startup, before doing anything else\nDATABASE_URL = require_env("DATABASE_URL")\nAPI_KEY = require_env("API_KEY")\n\nprint("Secrets loaded successfully")',
          caption: "Fail-fast environment variable loading",
        },
        {
          kind: "comparison",
          leftLabel: "Wrong — hardcoded secret",
          rightLabel: "Right — from environment",
          leftCode: '# NEVER DO THIS\nAPI_KEY = "sk-abc123secret"\npassword = "hunter2"',
          rightCode: 'import os\n\nAPI_KEY = os.environ["API_KEY"]\n# Or with python-dotenv:\n# from dotenv import load_dotenv\n# load_dotenv()\n# API_KEY = os.environ["API_KEY"]',
        },
      ],
      interactions: [
        {
          id: "s15-secrets-i1",
          kind: "multiple-choice",
          prompt: "What is the main risk of hardcoding an API key directly in Python source code?",
          beginnerPurpose: "Understand why secrets should not be in code",
          expectedConceptIds: ["secrets-management"],
          options: [
            { id: "a", text: "The code runs slower", isCorrect: false, explanation: "Performance is not the concern." },
            { id: "b", text: "The secret gets committed to version control and can be exposed", isCorrect: true, explanation: "Correct! Git history is permanent — secrets in code stay there forever." },
            { id: "c", text: "The key stops working after one use", isCorrect: false, explanation: "API keys don't expire just because they're in code." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think about what happens when you git commit and push" }],
          feedback: {
            correct: "Correct! Secrets in code end up in git history and can be leaked.",
            incorrect: "The problem is version control exposure — secrets in code get committed forever.",
          },
        },
        {
          id: "s15-secrets-i2",
          kind: "fill-code",
          prompt: "Complete the code to safely load a required API key from the environment",
          beginnerPurpose: "Practice os.environ access pattern",
          expectedConceptIds: ["env-variables"],
          codeTemplate:
            'import os\n\napi_key = os.___BLANK_1___.get("API_KEY")\nif not api_key:\n    raise RuntimeError("API_KEY environment variable is not set")\nprint("Key loaded")',
          blanks: [
            { placeholder: "___BLANK_1___", answer: "environ", caseSensitive: true },
          ],
          allowedAttempts: 3,
          hints: [{ level: "syntax", text: "os.environ is the dict-like object that holds environment variables" }],
          feedback: {
            correct: "Correct! os.environ holds all environment variables.",
            incorrect: "Use os.environ (not os.env or os.environment).",
          },
        },
        {
          id: "s15-secrets-i3",
          kind: "reorder-code",
          prompt: "Arrange these steps in the correct order for secure secret handling",
          beginnerPurpose: "Learn the secure secrets workflow",
          expectedConceptIds: ["secrets-management", "env-variables"],
          lines: [
            "Add .env to .gitignore",
            "Create .env file with SECRET_KEY=your-value",
            "In code: os.environ.get('SECRET_KEY')",
            "Set real value in production via platform env vars",
          ],
          correctOrder: [1, 0, 2, 3],
          allowedAttempts: 3,
          hints: [{ level: "structural", text: "Create the .env file, protect it from git, read it in code, set real values in prod" }],
          feedback: {
            correct: "Correct workflow: create .env → gitignore it → read in code → set real values in prod.",
            incorrect: "You must gitignore .env before any secrets end up in version control.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s15-secrets-i1", "s15-secrets-i2", "s15-secrets-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s15-dependency-management",
      stageId: "stage-15",
      title: "Dependency Management and Supply-Chain Risk",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Pin exact dependency versions to ensure reproducibility",
        "Understand supply-chain attack risk from third-party packages",
        "Use pip audit or safety to check for known vulnerabilities",
      ],
      prerequisites: ["s15-secrets-env-variables"],
      concepts: ["dependency-pinning"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Dependency Risk\n\nEvery package you install is code you trust to run on your machine. A compromised package can steal secrets, install malware, or exfiltrate data.\n\n**Supply-chain attacks** target the packages themselves — malicious code inserted into a legitimate package or published as a lookalike name.\n\nMinimise risk:\n- **Pin exact versions** (`requests==2.31.0` not `requests`)\n- **Use a lockfile** (pip-tools, uv, poetry all produce lockfiles)\n- **Audit regularly** (`pip-audit` or `safety check`)\n- **Minimise dependencies** — don't install what you don't need",
        },
        {
          kind: "code",
          language: "text",
          code: "# requirements.txt — pinned versions\nrequests==2.31.0\ncertifi==2024.2.2\nurllib3==2.2.1\ncharset-normalizer==3.3.2\nidna==3.7\n\n# Run vulnerability scan\n# pip-audit\n# → Found 0 known vulnerabilities",
          caption: "Pinned requirements.txt and audit",
        },
        {
          kind: "callout",
          variant: "warning",
          title: "Typosquatting is a real attack",
          body: "Attackers publish packages with names similar to popular ones (e.g. 'reqeusts' instead of 'requests'). Always verify the exact package name before installing.",
        },
      ],
      interactions: [
        {
          id: "s15-deps-i1",
          kind: "multiple-choice",
          prompt: "Why should you pin exact dependency versions (e.g. requests==2.31.0)?",
          beginnerPurpose: "Understand reproducibility through pinning",
          expectedConceptIds: ["dependency-pinning"],
          options: [
            { id: "a", text: "To prevent any new packages from being installed", isCorrect: false, explanation: "Pinning doesn't prevent installation, it controls which version." },
            { id: "b", text: "To ensure the same versions are installed in every environment", isCorrect: true, explanation: "Correct! Pinning ensures reproducible builds." },
            { id: "c", text: "To make pip install faster", isCorrect: false, explanation: "Speed is not the main benefit." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think about what happens when a new version of a dependency breaks your code" }],
          feedback: {
            correct: "Correct! Pinned versions ensure every install uses exactly the same code.",
            incorrect: "Version pinning ensures reproducibility — the same code runs in dev and production.",
          },
        },
        {
          id: "s15-deps-i2",
          kind: "multiple-choice",
          prompt: "What is a supply-chain attack in the context of Python packages?",
          beginnerPurpose: "Understand the threat model for dependencies",
          expectedConceptIds: ["dependency-pinning"],
          options: [
            { id: "a", text: "A bug in your own code that leaks data", isCorrect: false, explanation: "That's your code, not a supply-chain issue." },
            { id: "b", text: "Malicious code inserted into a third-party package you depend on", isCorrect: true, explanation: "Correct! Attackers target packages in the supply chain, not your code directly." },
            { id: "c", text: "A DDoS attack on PyPI", isCorrect: false, explanation: "DDoS is availability, not a supply-chain code attack." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "The 'supply chain' is all the packages your app depends on" }],
          feedback: {
            correct: "Correct! Supply-chain attacks compromise packages your code trusts.",
            incorrect: "Supply-chain attacks insert malicious code into packages you depend on.",
          },
        },
        {
          id: "s15-deps-i3",
          kind: "plain-language-explain",
          prompt: "Explain three practices to reduce dependency risk in a Python project",
          beginnerPurpose: "Articulate a dependency security strategy",
          expectedConceptIds: ["dependency-pinning"],
          code: "# requirements.txt\nrequests==2.31.0  # pinned\n\n# $ pip-audit\n# $ pip freeze > requirements.txt",
          keyPointsToHit: [
            "Pin exact versions in requirements",
            "Audit for known vulnerabilities",
            "Minimise the number of dependencies",
          ],
          sampleAnswer:
            "Three practices to reduce dependency risk: (1) Pin exact versions in requirements.txt so you always install the same code in every environment; (2) Audit your dependencies regularly with pip-audit to find known CVEs; (3) Minimise your dependency count — every package you add is a potential attack surface.",
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think: reproducibility, auditing, minimalism" }],
          feedback: {
            correct: "Well covered!",
            incorrect: "Cover: pinning, auditing, and minimising dependencies.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s15-deps-i1", "s15-deps-i2", "s15-deps-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s15-package-structure",
      stageId: "stage-15",
      title: "Package Structure and pyproject.toml",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Understand the pyproject.toml standard for Python packages",
        "Structure a minimal distributable Python package",
        "Distinguish src layout from flat layout",
      ],
      prerequisites: ["s15-dependency-management"],
      concepts: ["package-structure", "semantic-versioning"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Modern Python Packaging\n\nPEP 517/518 standardised packaging via `pyproject.toml`. This replaces `setup.py` and `setup.cfg` for new projects.\n\n**Minimal package structure (src layout):**\n```\nmy-package/\n  pyproject.toml\n  src/\n    my_package/\n      __init__.py\n      core.py\n  tests/\n    test_core.py\n  README.md\n```\n\nThe `src` layout prevents accidental imports from the project root during testing.",
        },
        {
          kind: "code",
          language: "toml",
          code: '[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n\n[project]\nname = "my-package"\nversion = "1.0.0"\ndescription = "A well-structured Python package"\nrequires-python = ">=3.12"\ndependencies = [\n    "requests>=2.31.0",\n]\n\n[project.optional-dependencies]\ndev = [\n    "pytest>=8.0",\n    "mypy>=1.8",\n]\n\n[tool.mypy]\nstrict = true\n\n[tool.pytest.ini_options]\ntestpaths = ["tests"]',
          caption: "Minimal pyproject.toml with hatchling",
        },
        {
          kind: "callout",
          variant: "info",
          title: "Semantic versioning: MAJOR.MINOR.PATCH",
          body: "1.2.3 — 1 is the MAJOR (breaking changes), 2 is MINOR (new features, backwards compatible), 3 is PATCH (bug fixes only). Breaking API changes must increment MAJOR.",
        },
      ],
      interactions: [
        {
          id: "s15-pkg-i1",
          kind: "multiple-choice",
          prompt: "In semantic versioning, when should you increment the MAJOR version number?",
          beginnerPurpose: "Understand semver meaning",
          expectedConceptIds: ["semantic-versioning"],
          options: [
            { id: "a", text: "When you fix a bug", isCorrect: false, explanation: "Bug fixes increment PATCH (1.2.3 → 1.2.4)." },
            { id: "b", text: "When you add a backwards-compatible feature", isCorrect: false, explanation: "New features increment MINOR (1.2.3 → 1.3.0)." },
            { id: "c", text: "When you make a breaking change to the public API", isCorrect: true, explanation: "Correct! Breaking changes require a MAJOR bump (1.2.3 → 2.0.0)." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "MAJOR.MINOR.PATCH — which one signals incompatibility?" }],
          feedback: {
            correct: "Correct! MAJOR versions signal breaking changes that require consumer updates.",
            incorrect: "MAJOR = breaking, MINOR = new features, PATCH = bug fixes.",
          },
        },
        {
          id: "s15-pkg-i2",
          kind: "predict-output",
          prompt: "What is the next version after 2.3.7 if you add a new backwards-compatible feature?",
          beginnerPurpose: "Apply semver rules",
          expectedConceptIds: ["semantic-versioning"],
          code: "# Current: 2.3.7\n# Change: added new function, no breaking changes\n# New version: ???\nprint('2.4.0')",
          expectedOutput: "2.4.0",
          allowedAttempts: 3,
          hints: [{ level: "concept", text: "New feature = MINOR bump, reset PATCH to 0" }],
          feedback: {
            correct: "Correct! MINOR 3→4, PATCH resets to 0 → 2.4.0",
            incorrect: "New backwards-compatible feature = MINOR bump. 2.3.7 → 2.4.0",
          },
        },
        {
          id: "s15-pkg-i3",
          kind: "multiple-choice",
          prompt: "What is the advantage of using the src layout (src/my_package/) over a flat layout?",
          beginnerPurpose: "Understand src layout benefits",
          expectedConceptIds: ["package-structure"],
          options: [
            { id: "a", text: "It makes the package smaller", isCorrect: false, explanation: "Layout doesn't affect package size." },
            { id: "b", text: "Tests can't accidentally import the uninstalled package from the project root", isCorrect: true, explanation: "Correct! The src layout forces you to install the package before testing, catching packaging bugs early." },
            { id: "c", text: "Python requires src layout for all packages", isCorrect: false, explanation: "src layout is a convention, not a requirement." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think about what Python's import system finds on sys.path" }],
          feedback: {
            correct: "Correct! src layout prevents import confusion during testing.",
            incorrect: "The src layout forces the package to be installed, preventing accidental root imports during testing.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s15-pkg-i1", "s15-pkg-i2", "s15-pkg-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
    {
      id: "s15-versioning-changelog",
      stageId: "stage-15",
      title: "Semantic Versioning and Changelogs",
      kind: "concept",
      difficulty: "advanced",
      objectives: [
        "Apply semantic versioning rules: MAJOR.MINOR.PATCH",
        "Decide which version segment to bump for each change type",
        "Write a useful CHANGELOG entry",
        "Understand the pyproject.toml version field",
      ],
      prerequisites: ["s15-package-structure"],
      concepts: ["semantic-versioning", "pyproject-toml", "supply-chain-risk"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Semantic Versioning\n\n**MAJOR.MINOR.PATCH** (e.g. `2.4.1`)\n\n| Segment | When to bump |\n|---------|-------------|\n| MAJOR | Breaking change — existing API removed or changed |\n| MINOR | New feature, backwards-compatible |\n| PATCH | Bug fix, no new features |\n\nWhen MAJOR bumps, reset MINOR and PATCH to 0.\nWhen MINOR bumps, reset PATCH to 0.",
        },
        {
          kind: "code",
          language: "python",
          code: "# pyproject.toml version field:\n# [project]\n# name = \"my-tool\"\n# version = \"2.3.1\"\n#\n# After a bug fix: version = \"2.3.2\"\n# After a new feature: version = \"2.4.0\"\n# After a breaking change: version = \"3.0.0\"\n\nfrom packaging.version import Version\n\nv = Version(\"1.9.3\")\nprint(v.major, v.minor, v.micro)  # 1 9 3\n\ndef classify_bump(old: str, new: str) -> str:\n    o, n = Version(old), Version(new)\n    if n.major > o.major:\n        return 'major'\n    if n.minor > o.minor:\n        return 'minor'\n    return 'patch'\n\nprint(classify_bump('1.3.1', '2.0.0'))  # major\nprint(classify_bump('1.3.1', '1.4.0'))  # minor",
          caption: "packaging.Version parses and compares semver strings correctly.",
        },
        {
          kind: "callout",
          variant: "tip",
          title: "Keep a CHANGELOG",
          body: "A CHANGELOG.md with sections for Added, Changed, Fixed, and Security tells users what changed in each release. This is especially important for the supply chain: users need to know if a dependency upgrade is safe.",
        },
        {
          kind: "why-matters",
          body: "Semantic versioning is a contract with your users. Breaking it destroys trust. A package that follows semver lets users safely pin to `~=1.3` (compatible releases) knowing minor/patch upgrades won't break their code.",
        },
      ],
      interactions: [
        {
          id: "s15-vc-mc-semver",
          kind: "multiple-choice",
          prompt: "Your library at `1.3.0` removes a public function. What is the new version?",
          beginnerPurpose: "Apply semver rules for breaking changes.",
          expectedConceptIds: ["semantic-versioning"],
          options: [
            { id: "a", text: "`1.3.1`", isCorrect: false, explanation: "Removing a public function is a breaking change — MAJOR must bump." },
            { id: "b", text: "`1.4.0`", isCorrect: false, explanation: "Minor bumps are for new features, not breaking changes." },
            { id: "c", text: "`2.0.0`", isCorrect: true, explanation: "Correct! Removing public API is a breaking change — bump MAJOR." },
            { id: "d", text: "`1.3.0`", isCorrect: false, explanation: "Any change requires a version bump." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Removing a public function breaks code that relied on it." }],
          feedback: {
            correct: "Correct! Breaking changes bump MAJOR → 2.0.0.",
            incorrect: "Removing a public API is a breaking change — bump MAJOR to `2.0.0`.",
          },
        },
        {
          id: "s15-vc-fill-semver",
          kind: "fill-code",
          prompt: "Fill in the new versions for each change starting from 2.3.1.",
          beginnerPurpose: "Practice semver arithmetic.",
          expectedConceptIds: ["semantic-versioning"],
          codeTemplate:
            "# Starting version: 2.3.1\n# Bug fix only       → ___BLANK_1___\n# New feature        → ___BLANK_2___\n# Breaking change    → ___BLANK_3___",
          blanks: [
            { placeholder: "___BLANK_1___", answer: "2.3.2", caseSensitive: true },
            { placeholder: "___BLANK_2___", answer: "2.4.0", caseSensitive: true },
            { placeholder: "___BLANK_3___", answer: "3.0.0", caseSensitive: true },
          ],
          allowedAttempts: 3,
          hints: [{ level: "concept", text: "Patch fix: +0.0.1. New feature: +0.1.0 reset patch. Breaking: +1.0.0 reset minor+patch." }],
          feedback: {
            correct: "Correct! 2.3.2, 2.4.0, 3.0.0.",
            incorrect: "Patch: 2.3.2. Feature: 2.4.0. Breaking: 3.0.0.",
          },
        },
        {
          id: "s15-vc-predict-version",
          kind: "predict-output",
          prompt: "What does this code print?",
          beginnerPurpose: "Trace Version object attributes.",
          expectedConceptIds: ["semantic-versioning", "pyproject-toml"],
          code: "from packaging.version import Version\nv = Version('3.11.2')\nprint(v.major)\nprint(v.minor)",
          expectedOutput: "3\n11",
          allowedAttempts: 3,
          hints: [{ level: "concept", text: ".major and .minor extract the MAJOR and MINOR parts." }],
          feedback: {
            correct: "Correct! major=3, minor=11.",
            incorrect: "Version('3.11.2').major=3 and .minor=11.",
          },
        },
        {
          id: "s15-vc-mc-supply-chain",
          kind: "multiple-choice",
          prompt: "A package named `requets` (note the typo) appears on PyPI. What kind of attack is this?",
          beginnerPurpose: "Recognise supply-chain attack patterns.",
          expectedConceptIds: ["supply-chain-risk"],
          options: [
            { id: "a", text: "A man-in-the-middle attack.", isCorrect: false, explanation: "MITM attacks intercept traffic; this is about package naming." },
            { id: "b", text: "Typosquatting — a malicious package impersonating a legitimate one.", isCorrect: true, explanation: "Correct! Attackers register misspelled package names hoping developers make typos." },
            { id: "c", text: "A dependency confusion attack.", isCorrect: false, explanation: "Dependency confusion exploits private vs public namespace — different from typosquatting." },
            { id: "d", text: "A zero-day exploit.", isCorrect: false, explanation: "Zero-days are vulnerabilities in software, not malicious packages." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "The name is almost identical to a popular package — one letter different." }],
          feedback: {
            correct: "Correct! Typosquatting exploits typing mistakes to deliver malicious code.",
            incorrect: "Malicious packages with names almost identical to popular packages is typosquatting.",
          },
        },
      ],
      reviewHooks: [
        { conceptId: "semantic-versioning", recallPrompt: "When do you bump MAJOR vs MINOR vs PATCH?", nextReviewAfterDays: 3 },
        { conceptId: "supply-chain-risk", recallPrompt: "What is typosquatting and how do you protect against it?", nextReviewAfterDays: 3 },
      ],
      masteryCriteria: {
        requiredInteractionIds: ["s15-vc-mc-semver", "s15-vc-fill-semver", "s15-vc-predict-version"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: ["semantic-versioning", "supply-chain-risk"],
      },
    },
    {
      id: "s15-security-review",
      stageId: "stage-15",
      title: "Security Review Checklist",
      kind: "debugging",
      difficulty: "advanced",
      objectives: [
        "Apply a security review checklist to Python code",
        "Identify common insecure patterns: shell injection, SQL injection conceptually, unsafe deserialization",
        "Apply the principle of least privilege",
      ],
      prerequisites: ["s15-package-structure"],
      concepts: ["secrets-management"],
      contentBlocks: [
        {
          kind: "text",
          markdown:
            "## Security Review Checklist\n\n- **No secrets in code** — all credentials from environment variables\n- **No shell injection** — never pass user input to `os.system()` or `subprocess` without validation\n- **Validate all external input** — API responses, user input, file contents\n- **Least privilege** — request only the permissions you need\n- **Dependency audit** — no known CVEs in dependencies\n- **Error messages don't leak** — stack traces and internal paths not shown to users",
        },
        {
          kind: "comparison",
          leftLabel: "Insecure — shell injection risk",
          rightLabel: "Secure — validated input",
          leftCode: 'import subprocess\n\n# DANGEROUS — user controls the command!\nuser_input = "world; rm -rf /"\nsubprocess.run(f"echo {user_input}", shell=True)',
          rightCode: 'import subprocess\n\n# Safe — no shell, args as list\nuser_input = "world"\nif user_input.isalpha():\n    subprocess.run(["echo", user_input], shell=False)',
        },
        {
          kind: "callout",
          variant: "danger",
          title: "Never use shell=True with user input",
          body: "When shell=True, the input is passed to a shell interpreter. A malicious user can inject shell commands. Always use shell=False and pass arguments as a list.",
        },
      ],
      interactions: [
        {
          id: "s15-security-i1",
          kind: "debug-code",
          prompt: "Fix this code — it's vulnerable to shell injection",
          beginnerPurpose: "Identify and fix a shell injection vulnerability",
          expectedConceptIds: ["secrets-management"],
          brokenCode: 'import subprocess\n\nfilename = input("Enter filename: ")  # could be "file.txt; rm -rf /"\nsubprocess.run(f"cat {filename}", shell=True)',
          bugDescription: "shell=True with user-controlled input allows command injection",
          fixedCode: 'import subprocess\nimport re\n\nfilename = input("Enter filename: ")\n# Validate: only allow alphanumeric, dots, hyphens, underscores\nif not re.match(r"^[a-zA-Z0-9._-]+$", filename):\n    raise ValueError("Invalid filename")\nsubprocess.run(["cat", filename], shell=False)',
          errorType: "SecurityError",
          allowedAttempts: 4,
          hints: [
            { level: "concept", text: "shell=True with user input is a shell injection vulnerability" },
            { level: "syntax", text: "Use shell=False and pass args as a list: ['cat', filename]" },
          ],
          feedback: {
            correct: "Correct! Validate input and use shell=False with args as a list.",
            incorrect: "Remove shell=True, validate the filename, and pass args as a list.",
          },
        },
        {
          id: "s15-security-i2",
          kind: "multiple-choice",
          prompt: "What is the principle of least privilege?",
          beginnerPurpose: "Understand a core security principle",
          expectedConceptIds: ["secrets-management"],
          options: [
            { id: "a", text: "Request only the minimum permissions needed for the task", isCorrect: true, explanation: "Correct! Least privilege minimises the damage if something goes wrong." },
            { id: "b", text: "Use the simplest possible code", isCorrect: false, explanation: "That's simplicity, not least privilege." },
            { id: "c", text: "Never give users any permissions", isCorrect: false, explanation: "It's minimum necessary, not zero." },
          ],
          allowMultiple: false,
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Ask: what is the minimum permission this code needs to do its job?" }],
          feedback: {
            correct: "Correct! Least privilege = only the permissions you actually need.",
            incorrect: "Least privilege means granting only the minimum permissions necessary.",
          },
        },
        {
          id: "s15-security-i3",
          kind: "plain-language-explain",
          prompt: "Explain why error messages should not include stack traces or internal paths when shown to users",
          beginnerPurpose: "Understand information leakage risks",
          expectedConceptIds: ["secrets-management"],
          code: '# Bad: leaks internal path and implementation details\nprint(f"Error at /home/user/app/database.py line 42: {secret_key}")\n\n# Good: user-friendly, no leakage\nprint("An error occurred. Please try again.")',
          keyPointsToHit: [
            "Stack traces reveal internal file paths and code structure",
            "This information helps attackers understand the system",
            "Users should see friendly messages, developers see full errors in logs",
          ],
          sampleAnswer:
            "Stack traces reveal internal file paths, function names, line numbers, and sometimes variable values. This information helps attackers map the application's structure and find weaknesses. Users should see a friendly error message with no internal details. Developers should see the full error in secure logs that users can't access.",
          allowedAttempts: 2,
          hints: [{ level: "concept", text: "Think about what information an attacker could extract from a stack trace" }],
          feedback: {
            correct: "Well explained! Information in error messages becomes intelligence for attackers.",
            incorrect: "Mention: internal paths reveal structure, and users vs developers need different error detail levels.",
          },
        },
      ],
      reviewHooks: [],
      masteryCriteria: {
        requiredInteractionIds: ["s15-security-i1", "s15-security-i2", "s15-security-i3"],
        minimumCorrectFraction: 0.8,
        reviewHookIds: [],
      },
    },
  ],
  project: {
    id: "s15-project",
    stageId: "stage-15",
    title: "Packaged Utility with Security Checklist",
    brief:
      "Structure a small Python utility as a proper package with pyproject.toml, load all configuration from environment variables, and apply the security checklist.",
    requirements: [
      "src layout with src/my_utility/__init__.py",
      "pyproject.toml with project metadata",
      "All config loaded from os.environ with require_env()",
      "No hardcoded secrets anywhere",
      "Shell operations use shell=False with validated input",
      "Error messages are user-friendly without stack traces",
    ],
    acceptanceCriteria: [
      "Package can be installed with pip install -e .",
      "Missing env vars cause a clear startup error",
      "Security checklist items all pass",
    ],
    conceptIds: ["secrets-management", "env-variables", "package-structure", "semantic-versioning"],
    difficulty: "advanced",
    starterCode:
      "# src/my_utility/__init__.py\nimport os\n\ndef require_env(key: str) -> str:\n    value = os.environ.get(key)\n    if not value:\n        raise RuntimeError(f\"Required: {key}\")\n    return value\n\n# Your utility code here\n",
  },
} satisfies Stage;
